### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by VeIix** [MishDotCom/Admin-Password-Cracker#1]
For step two where it said cd into directory
I typed C:\users\administrator.  It just says access denied

**Comment by MishDotCom** [comment]
Hi!
You need to cd in the directory of the <code>AdminPass.exe</code> in order to run it from the command line.

**Comment by VeIix** [comment]
> Hi!
> You need to cd in the directory of the `AdminPass.exe` in order to run it from the command line.

Where do I find that ?

**Comment by MishDotCom** [comment]
You download it from the releases tab.
link: https://github.com/MishDotCom/Admin-Password-Cracker/releases/download/v1.0/AdminPass.exe

**Comment by mmmmdwd** [comment]
![Screenshot 2022-06-02 100734](https://user-images.githubusercontent.com/83366219/171596446-8da8721f-bba1-499f-aba0-0174ee0f47ff.jpg)
Hi,
This is what I'm getting when I try to run the file, what do i do?
